#!/usr/local/bin/python3
import sys

print("Marking {} as done".format(sys.argv[1]))

# This function is called when a git push is ran.
# It will be passed a task ID that has is marked done.
# Exiting with a non zero exit code will not stop the push just warn the user and leave the id and will try the task on
# the next push

# The plugins will be ran from .git/gitdo/plugins/<name>. Loading config should be in this directory.
# See Trello example.