#!/usr/local/bin/python3

from urllib.parse import urlencode
from urllib.request import Request, urlopen, URLError, HTTPError
import json
import sys

if len(sys.argv) is not 2:
    print("not enough arguements")
    exit(1)

base_url = "https://api.trello.com/1/"
appkey = ""
token = ""

with open('.git/gitdo/secrets.json') as json_data:
    d = json.load(json_data)
    appkey = d["appkey"]
    token = d["token"]

url = "{}cards/{}?closed=false&key={}&token={}".format(base_url, sys.argv[1], appkey, token)

try:
    request = Request(url=url, method="PUT")
    resp = urlopen(request).read().decode()
    json_resp = json.loads(resp)
    print(json_resp)
except HTTPError as e:
    print("error: http error")
    exit(1)
except URLError as e:
    print("error: url error")
    exit(2)
