#!/usr/local/bin/python3

from urllib.parse import urlencode
from urllib.request import Request, urlopen

url = 'https://httpbin.org/post'    # Destination URL
post_fields = {'foo':'bar'}         # Post fields

request = Request(url, urlencode(post_fields).encode())
json = urlopen(request).read().decode()
print(json)
