#!/usr/local/bin/python3
# Using the python3 interpreter on mac - make sure the path is where yours is

from urllib.parse import urlencode
from urllib.request import Request, urlopen, URLError, HTTPError
import json
import sys

if len(sys.argv) is not 2:
    print("not enough arguements")
    exit(1)

base_url = "https://api.trello.com/1/"
repo_url = "https://github.com/nebbers1111/Example/blob/"
appkey = ""
token = ""
list_id = "5aa0057dae6f639766e9bff4"


task_arg = sys.argv[1]
task = json.loads(task_arg)

line_link = "{}{}/{}#L{}".format(repo_url, task["hash"], task["file_name"], task["file_line"])

desc = "{}#{}\ncommit {} on branch {}\n{}\n\n{}".format(
    task["file_name"], task["file_line"], task["hash"], task["branch"], task["author"], line_link)


card = {
    "name": task["task_name"],
    "desc": desc,
    "closed": "true",
    "idList": list_id,
}

with open('.git/gitdo/secrets.json') as json_data:
    d = json.load(json_data)
    appkey = d["appkey"]
    token = d["token"]

url = "{}cards?key={}&token={}".format(base_url, appkey, token)
post_fields = {
    "idList": list_id,
    "name": "test",
}

try:
    request = Request(url, urlencode(card).encode())
    resp = urlopen(request).read().decode()
    trello_card = json.loads(resp)
    print(trello_card['shortLink'])
except HTTPError as e:
    print("error: code={} message={}".format(e.code, e.reason))
    exit(1)
except URLError as e:
    print("error: "+ e.args)
    exit(2)
