#!/usr/local/bin/python3
from urllib.parse import urlencode
from urllib.request import Request, urlopen, URLError, HTTPError
import json
import helper
import sys  # arg[1]: id, arg[2]: task

# Exit if not given ID and task JSON
if len(sys.argv) is not 2 and len(sys.argv) is not 3:
    print("wrong number of arguments")
    exit(1)

conf = helper.get_config()

task_arg = sys.argv[1]  # Get json task
task = json.loads(task_arg)  # Get dict to read attributes

link = conf["remote_link"]
link = link.replace("{hash}", task["hash"])
link = link.replace("{file_name}", task["file_name"])
link = link.replace("{file_line}", str(task["file_line"]))
link = link.replace("{branch}", task["branch"])

desc = "{}#{}\nHash: '{}' on {}\nLink: {}\n{}".format(
    task["file_name"], task["file_line"], task["hash"], task["branch"], link, task["author"])

card = {
    "name": task["task_name"],
    "closed": "false",
    "desc": desc,
    "key": conf["key"],
    "token": conf["token"],
    "idList": conf["backlog_id"],
}

url = ""
method = "PUT"
if len(sys.argv) is 3:
    url = "{}cards/{}".format(helper.base_url, sys.argv[2])
else:
    url = "{}cards".format(helper.base_url)
    method = "POST"

try:
    request = Request(method=method, data=urlencode(card).encode(), url=url)
    resp = urlopen(request).read().decode()
    trello_card = json.loads(resp)
    print(trello_card['shortLink'])  # return cards short ID
except HTTPError as e:
    print("error: code={} message={}".format(e.code, e.reason))
    exit(1)
except URLError as e:
    print("error: " + e.args)
    exit(2)
