#!/usr/local/bin/python3
# No way of getting ID from trello without a card - so we create one that will be
# updated later - archived originally to not clutter, but does allow view in archive

from urllib.parse import urlencode  # encode card data
from urllib.request import Request, urlopen, URLError, HTTPError  # for making API calls
import json  # encode task and response
import sys  # for getting args - takes task as a json
import helper

# exit if not given only Task json
if len(sys.argv) is not 2:
    print("not enough arguements")
    exit(1)

conf = helper.get_config()

task_arg = sys.argv[1]  # Get json task
task = json.loads(task_arg)  # Get dict to read attributes

card = {
    "name": task["task_name"],
    "closed": "true",  # Archive task to not get in way until code is pushed
    "idList": conf["backlog_id"],
}

url = "{}cards?key={}&token={}".format(helper.base_url, conf["key"], conf["token"])

try:
    request = Request(method="POST", data=urlencode(card).encode(), url=url)
    resp = urlopen(request).read().decode()
    trello_card = json.loads(resp)
    print(trello_card['shortLink'])  # return cards short ID
except HTTPError as e:
    print("error: code={} message={}".format(e.code, e.reason))
    exit(1)
except URLError as e:
    print("error: " + e.args)
    exit(2)
