#!/usr/local/bin/python3
from urllib.parse import urlencode
from urllib.request import Request, urlopen, URLError, HTTPError
import json
import helper
import sys  # arg[1]: id, arg[2]: task

# Exit if not given ID and task JSON
if len(sys.argv) is not 3:
    print("wrong number of arguements")
    exit(1)

conf = helper.get_config()


task_arg = sys.argv[2]  # Get json task
task = json.loads(task_arg)  # Get dict to read attributes

link = conf["remote_link"]
link = link.replace("{hash}", task["hash"])
link = link.replace("{file_name}", task["file_name"])
link = link.replace("{file_line}", str(task["file_line"]))
link = link.replace("{branch}", task["branch"])


desc = "{}#{}\nHash: '{}' on {}\nLink: {}\n{}".format(
    task["file_name"], task["file_line"], task["hash"], task["branch"], link, task["author"])

card = {
    "closed": "false",
    "desc": desc,
    "key": conf["key"],
    "token": conf["token"],
}

url = "{}cards/{}".format(helper.base_url, sys.argv[1])

try:
    request = Request(method="PUT", data=urlencode(card).encode(), url=url)
    resp = urlopen(request).read().decode()
    json_resp = json.loads(resp)
    print(json_resp)
except HTTPError as e:
    print("error: code={} message={}".format(e.code, e.reason))
    exit(1)
except URLError as e:
    print("error: " + e.args)
    exit(2)
