#!/usr/local/bin/python3

from urllib.request import Request, urlopen, URLError, HTTPError # to make API call
import json # decode task and encode response
import sys # for args -> given task string (to be loaded as json)
import helper

# exit if not given ID
if len(sys.argv) is not 2:
    print("wrong number of arguements")
    exit(1)

conf = helper.get_config()

# Move the card to the new list
url = "{}cards/{}?idList={}&key={}&token={}".format(
    helper.base_url, sys.argv[1], conf["done_id"], conf["key"], conf["token"])

# Alternatively you could replace idList={} with closed=true to archive cards when done

try:
    request = Request(url=url, method="PUT")
    resp = urlopen(request).read().decode()
    json_resp = json.loads(resp)
    print(json_resp)
except HTTPError as e:
    print("error: code={} message={}".format(e.code, e.reason))
    exit(1)
except URLError as e:
    print("error: " + e.args)
    exit(2)
