#!/bin/sh
# Stash unstaged changes
echo "stashing changes"
git stash -q --keep-index

# echo "running gitdo"
# Edit your project files here
# python ../Gitdo/inspect_git.py "$(git diff --cached)"
.git/gitdo/Gitdo

echo "staging updated files"
# Stage updated files
git add -u

echo "applying original unstaged changes"
# Re-apply original unstaged changes
git stash pop -q
